### PR TITLE
Fixes #224

### LINKED ISSUE #224: BUG - Perks change position when clicked on
## Describe the bug
When a perk is clicked, other perks move position.

## To Reproduce
Click any perk.

## Expected behavior
Perks should not move, when clicked.

## Screenshots
grafik

### PR DESCRIPTION
**Pull request by danielniccoli**

### CODE REVIEW

**Comment by danielniccoli** [comment]
This slightly changes the design of clicked perks, but was the quickest solution to the issue.

**Comment by TwoAbove** [comment]
Closes #224

File: src/components/Icons/Clickable.tsx [hunk 1]
```diff
@@ -25,17 +25,17 @@ const Clickable = (props: IClickableProps | any) => {
 		setHovered(false);
 	};
 
-	const clickedStyles = clicked && 'border border-3 p-1 flex-shrink-1';
-	// TODO need to get centering correct so that there is not jittering
-	const hoverStyles = false && hovered && 'border';
+	// Clicked-style is prioritised, then hovered-style, otherwise fallback to default style.
+	const clickedOrHoveredStyle = clicked ? 'bg-info' : hovered ? 'bg-light' : 'bg-body'
```
Comment (TwoAbove) [inline src/components/Icons/Clickable.tsx:29]: I think the outline is a bit too thick. Can you make it a bit thinner and also add 
```js
style: {
  transition: '0.2s'
}
``` so that it doesn't change abruptly? Maybe even 0.1s, whatever feels more pleasant

Comment (danielniccoli) [reply src/components/Icons/Clickable.tsx:29]: Transition is added.

I'm not happy about the smaller padding. Primary, because we'd replace bootstrap-css with custom CSS. But also because with custom css, I don't get the perk icon perfectly centered. I did however add the Bootstrap class `rounded-1`, which makes the "border" (It's really just background color) a little easier on the eye.

Bootstrap `p-1` class:
image

Custom style `padding: 0.175rem`
image

Comment (TwoAbove) [reply src/components/Icons/Clickable.tsx:29]: I like the rounded with p-1! 
Let's keep that
